default_install_hook_types: [pre-commit, commit-msg]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        entry: cargo +nightly fmt
        args: ["--manifest-path", "./backend/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "./backend/Cargo.toml", "--"]

-   repo: https://github.com/hadolint/hadolint/
    rev: v2.12.0
    hooks:
    -   id: hadolint-docker

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
      - id: ruff
      - id: ruff-format

-   repo: local
    hooks:
    -   id: prettier
        name: Prettier
        description: Format Svelte/TS code using prettier
        entry: npm run format --prefix frontend
        language: node
        files: \.(ts|js|svelte|html)$
        pass_filenames: false
    -   id: typecheck
        name: Typechecking
        description: Typecheck TypeScript files
        entry: npm run check --prefix frontend
        language: node
        files: \.(ts|svelte)$
    -   id: commit-message
        name: Commit Message
        stages:
            - commit-msg
        description: Check commit message adheres to conventional commit format
        entry: scripts/commit-msg
        language: system
    -   id: mypy
        name: mypy strict
        verbose: true
        entry: ./scripts/run_mypy.sh
        language: python
        'types_or': [python, pyi]
