version: '3.1'

services:
  app:
    build: ./
    image: kroeg
    ports:
      - 8080:8000
  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
