### Who Am I
GET {{base}}/session/who
Accept: application/json

### Login User
POST {{base}}/session/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

email = some.user@gmail.com &
password = somepassw0rdthatisok


### Create User
POST {{base}}/session/create
Content-Type: application/x-www-form-urlencoded
Accept: application/json

email = some.user@gmail.com &
password = somepassw0rdthatisok


### Logout
POST {{base}}/session/logout
Accept: application/json
