/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LocationResponse {
	coordinates: Coordinate;
	description?: string | null;
	id: number;
	imageurl?: string | null;
	name: string;
}
export interface Coordinate {
	x: number;
	y: number;
}
